server:
  port: 7983

spring:
  application:
    name: RedisStudy
  swagger2:
    enabled: true
# 在springboot2.6.x结合swagger2.9.x会提示 documentationPluginsBootstrapper 空指针异常
# 原因是 springboot 2.6.x 中将 springMVC 默认路由匹配策略从 AntPathMatcher 更改为 PathPatternParser
# 导致出错，解决办法就是 切换回 ant_path_matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# ==========================  Redis 单机 ==========================
#  redis:
#    database: 0
##    host: 192.168.58.10
##    port: 16380
#    host: 192.168.111.36
#    port: 16379
#    password: 123456
#    letture:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms

# ==========================  Redis 集群 ==========================
  redis:
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.111.36:16301
        - 192.168.111.36:16302
        - 192.168.111.36:16303
        - 192.168.111.36:16304
        - 192.168.111.36:16305
        - 192.168.111.36:16306
    letture:
      # 支持集群拓扑动态感知刷新 默认为 false，开启后，当主从节点发生变化后，随之改变
      cluster:
        refresh:
          period: 2000
          adaptive: true
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    password: 123456


logging:
  level:
    root: info
  file:
    name: ./logs/springboot-jedis-redis7.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


